image: paperspace/gradient-base:pt112-tf29-jax0314-py39-20220803
port: 8501
command:
  - /bin/sh
  - '-c'
  - |
    cd /opt/repos/repo
    bash startup.sh
    pip install -r requirements.txt
    streamlit run app.py
models:
  - id: mo3uv7h4vnbbax
    path: /opt/models
repositories:
  dataset: ds9oprlnw80r706
  mountPath: /opt/repos
  repositories:
    - url: https://github.com/joshua-paperspace/stable-diffusion-app
      name: repo
      ref: main
resources:
  replicas: 1
  instanceType: A4000
